  if (!process.env.SAUCE_USERNAME || !process.env.SAUCE_ACCESS_KEY) {
    console.log('Make sure the SAUCE_USERNAME and SAUCE_ACCESS_KEY environment variables are set.')
    process.exit(1)
  }

  // Browsers to run on Sauce Labs
  // Check out https://saucelabs.com/platforms for all browser/OS combos
  var customLaunchers = {
    sl_chrome: {
      base: 'SauceLabs',
      browserName: 'chrome',
    },
    sl_firefox: {
      base: 'SauceLabs',
      browserName: 'firefox',
    },
    sl_edge: {
      base: 'SauceLabs',
      platform: "Windows 10",
      browserName: "microsoftedge"
    },
    sl_safari: {
      base: 'SauceLabs',
      platform: 'OS X 10.13',
      browserName: 'safari',
    },
    // sl_ie_11: {
    //   base: 'SauceLabs',
    //   browserName: 'internet explorer',
    //   platform: 'Windows 8.1',
    //   version: '11'
    // }
  }

  config.set({
    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: __dirname.replace('node_modules/joomla-javascript-tests/src', ''),

    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['fixture', 'jasmine'],

    //

    // list of files / patterns to load in the browser
    files: [
      './node_modules/joomla-javascript-tests/src/**/fixtures/*.html',

      // Include the webcomponents polyfills
      { pattern: 'media/vendor/webcomponentsjs/js/webcomponents-sd-ce-pf.js', loaded: true, served: true, watch: false },

	  // Load the files to test against
	  // Attention: tests should be written in ES5!!!
      { pattern: 'media/system/webcomponents/css/joomla-field-switcher.css', loaded: true, served: true, watch: false },
      { pattern: 'media/system/webcomponents/js/joomla-field-switcher.js', loaded: true, served: true, watch: false },


      // Load the tests definitions files
      'node_modules/joomla-javascript-tests/src/joomla-switcher/*.spec.js',

    ],

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
      '**/*.html': ['html2js'],
      '**/*.json': ['json_fixtures'],
    },

    // web server port
    port: 9876,

    // enable / disable colors in the output (reporters and logs)
    colors: true,

    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.DEBUG,

    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: false,

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false,

    // list of plugins
    plugins: [
      'karma-fixture',
      'karma-html2js-preprocessor',
      'karma-json-fixtures-preprocessor',
      'karma-jasmine',
      'karma-sauce-launcher',
      'karma-verbose-reporter'
    ],

    reporters: ['progress', 'saucelabs'],


    sauceLabs: {
      testName: 'Joomla 4 ES6 scripts tests',
      recordScreenshots: false,
      connectOptions: {
        port: 5758,
        logfile: 'sauce_connect.log'
      },
      public: 'public',
      connectOptions: {
        // username: user.username,
        // accessKey: user.accesskey,
        tunnelIdentifier: 'autoGeneratedTunnelID'
      }
    },
    // Increase timeout in case connection in CI is slow
    captureTimeout: 120000,
    customLaunchers: customLaunchers,
    browsers: Object.keys(customLaunchers),
    singleRun: true
  });
